


set_target (avformat)

add_library (${TARGET} OBJECT
       allformats.c
       av1.c
       avformat.c
       avio.c
       aviobuf.c
       codecstring.c
       demux.c
       demux_utils.c
       dump.c
       dv.c
       format.c
       id3v1.c
       id3v2.c
       isom_tags.c
       lcevc.c
       metadata.c
       mux.c
       mux_utils.c
       nal.c
       options.c
       os_support.c
       packet_list.c
       protocols.c
       riff.c
       sdp.c
       seek.c
       url.c
       urldecode.c
       utils.c
       version.c
       vpcc.c
)

add_sources_if (HAVE_LIBC_MSVCRT file_open.c)

# subsystems
add_sources_if (CONFIG_CBS_APV_LAVF cbs_apv.c cbs.c)
add_sources_if (CONFIG_CBS_AV1_LAVF cbs_av1.c cbs.c)
add_sources_if (CONFIG_ISO_MEDIA isom.c)
add_sources_if (CONFIG_ISO_WRITER avc.c hevc.c vvc.c)
add_sources_if (CONFIG_IAMFDEC iamf_reader.c iamf_parse.c iamf.c)
add_sources_if (CONFIG_IAMFENC iamf_writer.c iamf.c)
add_sources_if (CONFIG_NETWORK network.c)
add_sources_if (CONFIG_RIFFDEC riffdec.c)
add_sources_if (CONFIG_RIFFENC riffenc.c)
add_sources_if (CONFIG_RTPDEC rdt.c
                                            rtp.c
                                            rtpdec.c
                                            rtpdec_ac3.c
                                            rtpdec_amr.c
                                            rtpdec_asf.c
                                            rtpdec_av1.c
                                            rtpdec_dv.c
                                            rtpdec_g726.c
                                            rtpdec_h261.c
                                            rtpdec_h263.c
                                            rtpdec_h263_rfc2190.c
                                            rtpdec_h264.c
                                            rtpdec_hevc.c
                                            rtpdec_ilbc.c
                                            rtpdec_jpeg.c
                                            rtpdec_latm.c
                                            rtpdec_mpa_robust.c
                                            rtpdec_mpeg12.c
                                            rtpdec_mpeg4.c
                                            rtpdec_mpegts.c
                                            rtpdec_opus.c
                                            rtpdec_qcelp.c
                                            rtpdec_qdm2.c
                                            rtpdec_qt.c
                                            rtpdec_rfc4175.c
                                            rtpdec_svq3.c
                                            rtpdec_vc2hq.c
                                            rtpdec_vp8.c
                                            rtpdec_vp9.c
                                            rtpdec_xiph.c)
add_sources_if (CONFIG_RTPENC_CHAIN rtpenc_chain.c rtp.c)
add_sources_if (CONFIG_SRTP srtp.c)

# muxers/demuxers
add_sources_if (CONFIG_A64_MUXER a64.c rawenc.c)
add_sources_if (CONFIG_AA_DEMUXER aadec.c)
add_sources_if (CONFIG_AAC_DEMUXER aacdec.c apetag.c img2.c rawdec.c)
add_sources_if (CONFIG_AAX_DEMUXER aaxdec.c)
add_sources_if (CONFIG_AC3_DEMUXER ac3dec.c rawdec.c)
add_sources_if (CONFIG_AC3_MUXER rawenc.c)
add_sources_if (CONFIG_AC4_DEMUXER ac4dec.c)
add_sources_if (CONFIG_AC4_MUXER ac4enc.c)
add_sources_if (CONFIG_ACE_DEMUXER acedec.c)
add_sources_if (CONFIG_ACM_DEMUXER acm.c rawdec.c)
add_sources_if (CONFIG_ACT_DEMUXER act.c)
add_sources_if (CONFIG_ADF_DEMUXER bintext.c sauce.c)
add_sources_if (CONFIG_ADP_DEMUXER adp.c)
add_sources_if (CONFIG_ADS_DEMUXER ads.c)
add_sources_if (CONFIG_ADTS_MUXER adtsenc.c apetag.c img2.c id3v2enc.c)
add_sources_if (CONFIG_ADX_DEMUXER adxdec.c rawdec.c)
add_sources_if (CONFIG_ADX_MUXER rawenc.c)
add_sources_if (CONFIG_AEA_DEMUXER aeadec.c pcm.c)
add_sources_if (CONFIG_AEA_MUXER aeaenc.c rawenc.c)
add_sources_if (CONFIG_AFC_DEMUXER afc.c)
add_sources_if (CONFIG_AIFF_DEMUXER aiffdec.c aiff.c pcm.c mov_chan.c replaygain.c)
add_sources_if (CONFIG_AIFF_MUXER aiffenc.c aiff.c id3v2enc.c)
add_sources_if (CONFIG_AIX_DEMUXER aixdec.c)
add_sources_if (CONFIG_ALP_DEMUXER alp.c)
add_sources_if (CONFIG_ALP_MUXER alp.c rawenc.c)
add_sources_if (CONFIG_AMR_DEMUXER amr.c rawdec.c)
add_sources_if (CONFIG_AMR_MUXER amr.c rawenc.c)
add_sources_if (CONFIG_AMRNB_DEMUXER amr.c rawdec.c)
add_sources_if (CONFIG_AMRWB_DEMUXER amr.c rawdec.c)
add_sources_if (CONFIG_AMV_MUXER amvenc.c)
add_sources_if (CONFIG_ANM_DEMUXER anm.c)
add_sources_if (CONFIG_APAC_DEMUXER apac.c rawdec.c)
add_sources_if (CONFIG_APC_DEMUXER apc.c)
add_sources_if (CONFIG_APE_DEMUXER ape.c apetag.c img2.c)
add_sources_if (CONFIG_APM_DEMUXER apm.c)
add_sources_if (CONFIG_APM_MUXER apm.c rawenc.c)
add_sources_if (CONFIG_APNG_DEMUXER apngdec.c)
add_sources_if (CONFIG_APNG_MUXER apngenc.c)
add_sources_if (CONFIG_APTX_DEMUXER aptxdec.c)
add_sources_if (CONFIG_APTX_MUXER rawenc.c)
add_sources_if (CONFIG_APTX_HD_DEMUXER aptxdec.c)
add_sources_if (CONFIG_APTX_HD_MUXER rawenc.c)
add_sources_if (CONFIG_APV_DEMUXER apvdec.c)
add_sources_if (CONFIG_APV_MUXER apvenc.c)
add_sources_if (CONFIG_AQTITLE_DEMUXER aqtitledec.c subtitles.c)
add_sources_if (CONFIG_ARGO_ASF_DEMUXER argo_asf.c)
add_sources_if (CONFIG_ARGO_ASF_MUXER argo_asf.c)
add_sources_if (CONFIG_ARGO_BRP_DEMUXER argo_brp.c argo_asf.c)
add_sources_if (CONFIG_ARGO_CVG_DEMUXER argo_cvg.c)
add_sources_if (CONFIG_ARGO_CVG_MUXER argo_cvg.c)
add_sources_if (CONFIG_ASF_DEMUXER asfdec_f.c asf.c asfcrypt.c asf_tags.c avlanguage.c)
add_sources_if (CONFIG_ASF_O_DEMUXER asfdec_o.c asf.c asfcrypt.c asf_tags.c avlanguage.c)
add_sources_if (CONFIG_ASF_MUXER asfenc.c asf.c asf_tags.c avlanguage.c)
add_sources_if (CONFIG_ASS_DEMUXER assdec.c subtitles.c)
add_sources_if (CONFIG_ASS_MUXER assenc.c)
add_sources_if (CONFIG_AST_DEMUXER ast.c astdec.c)
add_sources_if (CONFIG_AST_MUXER ast.c astenc.c)
add_sources_if (CONFIG_AU_DEMUXER au.c pcm.c)
add_sources_if (CONFIG_AU_MUXER au.c rawenc.c)
add_sources_if (CONFIG_AVI_DEMUXER avidec.c)
add_sources_if (CONFIG_AVI_MUXER avienc.c mpegtsenc.c avlanguage.c rawutils.c)
add_sources_if (CONFIG_AVM2_MUXER swfenc.c swf.c)
add_sources_if (CONFIG_AVR_DEMUXER avr.c pcm.c)
add_sources_if (CONFIG_AVS_DEMUXER avs.c voc_packet.c voc.c)
add_sources_if (CONFIG_AVS2_DEMUXER avs2dec.c rawdec.c)
add_sources_if (CONFIG_AVS2_MUXER rawenc.c)
add_sources_if (CONFIG_AVS3_DEMUXER avs3dec.c rawdec.c)
add_sources_if (CONFIG_AVS3_MUXER rawenc.c)
add_sources_if (CONFIG_BETHSOFTVID_DEMUXER bethsoftvid.c)
add_sources_if (CONFIG_BFI_DEMUXER bfi.c)
add_sources_if (CONFIG_BINK_DEMUXER bink.c)
add_sources_if (CONFIG_BINKA_DEMUXER binka.c)
add_sources_if (CONFIG_BINTEXT_DEMUXER bintext.c sauce.c)
add_sources_if (CONFIG_BIT_DEMUXER bit.c)
add_sources_if (CONFIG_BIT_MUXER bit.c)
add_sources_if (CONFIG_BITPACKED_DEMUXER rawvideodec.c)
add_sources_if (CONFIG_BMV_DEMUXER bmv.c)
add_sources_if (CONFIG_BOA_DEMUXER boadec.c)
add_sources_if (CONFIG_BONK_DEMUXER bonk.c rawdec.c)
add_sources_if (CONFIG_BFSTM_DEMUXER brstm.c)
add_sources_if (CONFIG_BRSTM_DEMUXER brstm.c)
add_sources_if (CONFIG_C93_DEMUXER c93.c voc_packet.c voc.c)
add_sources_if (CONFIG_CAF_DEMUXER cafdec.c caf.c mov_chan.c mov_esds.c)
add_sources_if (CONFIG_CAF_MUXER cafenc.c caf.c riff.c)
add_sources_if (CONFIG_CAVSVIDEO_DEMUXER cavsvideodec.c rawdec.c)
add_sources_if (CONFIG_CAVSVIDEO_MUXER rawenc.c)
add_sources_if (CONFIG_CDG_DEMUXER cdg.c)
add_sources_if (CONFIG_CDXL_DEMUXER cdxl.c)
add_sources_if (CONFIG_CINE_DEMUXER cinedec.c)
add_sources_if (CONFIG_CODEC2_DEMUXER codec2.c pcm.c)
add_sources_if (CONFIG_CODEC2_MUXER codec2.c rawenc.c)
add_sources_if (CONFIG_CODEC2RAW_DEMUXER codec2.c pcm.c)
add_sources_if (CONFIG_CODEC2RAW_MUXER rawenc.c)
add_sources_if (CONFIG_CONCAT_DEMUXER concatdec.c)
add_sources_if (CONFIG_CRC_MUXER crcenc.c)
add_sources_if (CONFIG_DATA_DEMUXER rawdec.c)
add_sources_if (CONFIG_DATA_MUXER rawenc.c)
add_sources_if (CONFIG_DASH_MUXER dash.c dashenc.c hlsplaylist.c)
add_sources_if (CONFIG_DASH_DEMUXER dash.c dashdec.c)
add_sources_if (CONFIG_DAUD_DEMUXER dauddec.c)
add_sources_if (CONFIG_DAUD_MUXER daudenc.c)
add_sources_if (CONFIG_DCSTR_DEMUXER dcstr.c)
add_sources_if (CONFIG_DERF_DEMUXER derf.c pcm.c)
add_sources_if (CONFIG_DFA_DEMUXER dfa.c)
add_sources_if (CONFIG_DFPWM_DEMUXER dfpwmdec.c pcm.c)
add_sources_if (CONFIG_DFPWM_MUXER rawenc.c)
add_sources_if (CONFIG_DHAV_DEMUXER dhav.c)
add_sources_if (CONFIG_DIRAC_DEMUXER diracdec.c rawdec.c)
add_sources_if (CONFIG_DIRAC_MUXER rawenc.c)
add_sources_if (CONFIG_DNXHD_DEMUXER dnxhddec.c rawdec.c)
add_sources_if (CONFIG_DNXHD_MUXER rawenc.c)
add_sources_if (CONFIG_DSF_DEMUXER dsfdec.c)
add_sources_if (CONFIG_DSICIN_DEMUXER dsicin.c)
add_sources_if (CONFIG_DSS_DEMUXER dss.c)
add_sources_if (CONFIG_DTSHD_DEMUXER dtshddec.c)
add_sources_if (CONFIG_DTS_DEMUXER dtsdec.c rawdec.c)
add_sources_if (CONFIG_DTS_MUXER rawenc.c)
add_sources_if (CONFIG_DV_MUXER dvenc.c)
add_sources_if (CONFIG_DVBSUB_DEMUXER dvbsub.c rawdec.c)
add_sources_if (CONFIG_DVBTXT_DEMUXER dvbtxt.c rawdec.c)
add_sources_if (CONFIG_DVDVIDEO_DEMUXER dvdvideodec.c dvdclut.c)
add_sources_if (CONFIG_DXA_DEMUXER dxa.c)
add_sources_if (CONFIG_EA_CDATA_DEMUXER eacdata.c)
add_sources_if (CONFIG_EA_DEMUXER electronicarts.c)
add_sources_if (CONFIG_EAC3_DEMUXER ac3dec.c rawdec.c)
add_sources_if (CONFIG_EAC3_MUXER rawenc.c)
add_sources_if (CONFIG_EPAF_DEMUXER epafdec.c pcm.c)
add_sources_if (CONFIG_FFMETADATA_DEMUXER ffmetadec.c)
add_sources_if (CONFIG_FFMETADATA_MUXER ffmetaenc.c)
add_sources_if (CONFIG_FIFO_MUXER fifo.c)
add_sources_if (CONFIG_FILMSTRIP_DEMUXER filmstripdec.c)
add_sources_if (CONFIG_FILMSTRIP_MUXER filmstripenc.c rawenc.c)
add_sources_if (CONFIG_FITS_DEMUXER fitsdec.c)
add_sources_if (CONFIG_FITS_MUXER fitsenc.c)
add_sources_if (CONFIG_FLAC_DEMUXER flacdec.c rawdec.c
                                            flac_picture.c
                                            oggparsevorbis.c
                                            replaygain.c
                                            vorbiscomment.c)
add_sources_if (CONFIG_FLAC_MUXER flacenc.c flacenc_header.c vorbiscomment.c)
add_sources_if (CONFIG_FLIC_DEMUXER flic.c)
add_sources_if (CONFIG_FLV_DEMUXER flvdec.c)
add_sources_if (CONFIG_LIVE_FLV_DEMUXER flvdec.c)
add_sources_if (CONFIG_FLV_MUXER flvenc.c)
add_sources_if (CONFIG_FOURXM_DEMUXER 4xm.c)
add_sources_if (CONFIG_FRAMECRC_MUXER framecrcenc.c framehash.c)
add_sources_if (CONFIG_FRAMEHASH_MUXER hashenc.c framehash.c)
add_sources_if (CONFIG_FRAMEMD5_MUXER hashenc.c framehash.c)
add_sources_if (CONFIG_FRM_DEMUXER frmdec.c)
add_sources_if (CONFIG_FSB_DEMUXER fsb.c)
add_sources_if (CONFIG_FWSE_DEMUXER fwse.c pcm.c)
add_sources_if (CONFIG_GIF_MUXER gif.c)
add_sources_if (CONFIG_GIF_DEMUXER gifdec.c)
add_sources_if (CONFIG_GSM_DEMUXER gsmdec.c)
add_sources_if (CONFIG_GSM_MUXER rawenc.c)
add_sources_if (CONFIG_GXF_DEMUXER gxf.c)
add_sources_if (CONFIG_GXF_MUXER gxfenc.c)
add_sources_if (CONFIG_G722_DEMUXER g722.c rawdec.c)
add_sources_if (CONFIG_G722_MUXER rawenc.c)
add_sources_if (CONFIG_G723_1_DEMUXER g723_1.c)
add_sources_if (CONFIG_G723_1_MUXER rawenc.c)
add_sources_if (CONFIG_G726_DEMUXER g726.c)
add_sources_if (CONFIG_G726_MUXER rawenc.c)
add_sources_if (CONFIG_G726LE_DEMUXER g726.c)
add_sources_if (CONFIG_G726LE_MUXER rawenc.c)
add_sources_if (CONFIG_G728_DEMUXER g728dec.c)
add_sources_if (CONFIG_G729_DEMUXER g729dec.c)
add_sources_if (CONFIG_GDV_DEMUXER gdv.c)
add_sources_if (CONFIG_GENH_DEMUXER genh.c)
add_sources_if (CONFIG_H261_DEMUXER h261dec.c rawdec.c)
add_sources_if (CONFIG_H261_MUXER rawenc.c)
add_sources_if (CONFIG_H263_DEMUXER h263dec.c rawdec.c)
add_sources_if (CONFIG_H263_MUXER rawenc.c)
add_sources_if (CONFIG_H264_DEMUXER h264dec.c rawdec.c)
add_sources_if (CONFIG_H264_MUXER rawenc.c)
add_sources_if (CONFIG_HASH_MUXER hashenc.c)
add_sources_if (CONFIG_HCA_DEMUXER hca.c)
add_sources_if (CONFIG_HCOM_DEMUXER hcom.c pcm.c)
add_sources_if (CONFIG_HDS_MUXER hdsenc.c)
add_sources_if (CONFIG_HEVC_DEMUXER hevcdec.c rawdec.c)
add_sources_if (CONFIG_HEVC_MUXER rawenc.c)
add_sources_if (CONFIG_EVC_DEMUXER evcdec.c rawdec.c)
add_sources_if (CONFIG_EVC_MUXER rawenc.c)
add_sources_if (CONFIG_HLS_DEMUXER hls.c hls_sample_encryption.c)
add_sources_if (CONFIG_HLS_MUXER hlsenc.c hlsplaylist.c)
add_sources_if (CONFIG_HNM_DEMUXER hnm.c)
add_sources_if (CONFIG_HXVS_DEMUXER hxvs.c)
add_sources_if (CONFIG_IAMF_DEMUXER iamfdec.c)
add_sources_if (CONFIG_IAMF_MUXER iamfenc.c)
add_sources_if (CONFIG_ICO_DEMUXER icodec.c)
add_sources_if (CONFIG_ICO_MUXER icoenc.c)
add_sources_if (CONFIG_IDCIN_DEMUXER idcin.c)
add_sources_if (CONFIG_IDF_DEMUXER bintext.c sauce.c)
add_sources_if (CONFIG_IFF_DEMUXER iff.c)
add_sources_if (CONFIG_IFV_DEMUXER ifv.c)
add_sources_if (CONFIG_ILBC_DEMUXER ilbc.c)
add_sources_if (CONFIG_ILBC_MUXER ilbc.c rawenc.c)
add_sources_if (CONFIG_IMAGE2_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE2_MUXER img2enc.c img2.c)
add_sources_if (CONFIG_IMAGE2PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE2PIPE_MUXER img2enc.c img2.c)
add_sources_if (CONFIG_IMAGE2_ALIAS_PIX_DEMUXER img2_alias_pix.c)
add_sources_if (CONFIG_IMAGE2_BRENDER_PIX_DEMUXER img2_brender_pix.c)
add_sources_if (CONFIG_IMAGE_BMP_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_CRI_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_DDS_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_DPX_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_EXR_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_GEM_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_GIF_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_HDR_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_J2K_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_JPEG_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_JPEGLS_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_JPEGXL_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_JPEGXS_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_PAM_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_PBM_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_PCX_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_PFM_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_PGMYUV_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_PGM_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_PGX_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_PHM_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_PHOTOCD_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_PICTOR_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_PNG_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_PPM_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_PSD_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_QDRAW_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_QOI_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_SGI_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_SVG_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_SUNRAST_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_TIFF_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_VBN_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_WEBP_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_XBM_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_XPM_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMAGE_XWD_PIPE_DEMUXER img2dec.c img2.c)
add_sources_if (CONFIG_IMF_DEMUXER imfdec.c imf_cpl.c)
add_sources_if (CONFIG_INGENIENT_DEMUXER ingenientdec.c rawdec.c)
add_sources_if (CONFIG_IPMOVIE_DEMUXER ipmovie.c)
add_sources_if (CONFIG_IPU_DEMUXER ipudec.c rawdec.c)
add_sources_if (CONFIG_IRCAM_DEMUXER ircamdec.c ircam.c pcm.c)
add_sources_if (CONFIG_IRCAM_MUXER ircamenc.c ircam.c rawenc.c)
add_sources_if (CONFIG_ISS_DEMUXER iss.c)
add_sources_if (CONFIG_IV8_DEMUXER iv8.c)
add_sources_if (CONFIG_IVF_DEMUXER ivfdec.c)
add_sources_if (CONFIG_IVF_MUXER ivfenc.c)
add_sources_if (CONFIG_IVR_DEMUXER rmdec.c rm.c rmsipr.c)
add_sources_if (CONFIG_JACOSUB_DEMUXER jacosubdec.c subtitles.c)
add_sources_if (CONFIG_JACOSUB_MUXER jacosubenc.c rawenc.c)
add_sources_if (CONFIG_JPEGXL_ANIM_DEMUXER jpegxl_anim_dec.c)
add_sources_if (CONFIG_JV_DEMUXER jvdec.c)
add_sources_if (CONFIG_KUX_DEMUXER flvdec.c)
add_sources_if (CONFIG_KVAG_DEMUXER kvag.c)
add_sources_if (CONFIG_KVAG_MUXER kvag.c rawenc.c)
add_sources_if (CONFIG_LAF_DEMUXER lafdec.c)
add_sources_if (CONFIG_LATM_MUXER latmenc.c rawenc.c)
add_sources_if (CONFIG_LC3_DEMUXER lc3.c)
add_sources_if (CONFIG_LC3_MUXER lc3.c)
add_sources_if (CONFIG_LMLM4_DEMUXER lmlm4.c)
add_sources_if (CONFIG_LOAS_DEMUXER loasdec.c rawdec.c)
add_sources_if (CONFIG_LUODAT_DEMUXER luodatdec.c)
add_sources_if (CONFIG_LRC_DEMUXER lrcdec.c lrc.c subtitles.c)
add_sources_if (CONFIG_LRC_MUXER lrcenc.c lrc.c)
add_sources_if (CONFIG_LVF_DEMUXER lvfdec.c)
add_sources_if (CONFIG_LXF_DEMUXER lxfdec.c)
add_sources_if (CONFIG_M4V_DEMUXER m4vdec.c rawdec.c)
add_sources_if (CONFIG_M4V_MUXER rawenc.c)
add_sources_if (CONFIG_MATROSKA_DEMUXER matroskadec.c matroska.c
                                            flac_picture.c rmsipr.c
                                            oggparsevorbis.c vorbiscomment.c
                                            qtpalette.c replaygain.c dovi_isom.c)
add_sources_if (CONFIG_MATROSKA_MUXER matroskaenc.c matroska.c
                                            flacenc_header.c avlanguage.c
                                            vorbiscomment.c wv.c dovi_isom.c)
add_sources_if (CONFIG_MCA_DEMUXER mca.c)
add_sources_if (CONFIG_MCC_DEMUXER mccdec.c subtitles.c)
add_sources_if (CONFIG_MCC_MUXER mccenc.c)
add_sources_if (CONFIG_MD5_MUXER hashenc.c)
add_sources_if (CONFIG_MGSTS_DEMUXER mgsts.c)
add_sources_if (CONFIG_MICRODVD_DEMUXER microdvddec.c subtitles.c)
add_sources_if (CONFIG_MICRODVD_MUXER microdvdenc.c)
add_sources_if (CONFIG_MJPEG_2000_DEMUXER rawdec.c mj2kdec.c)
add_sources_if (CONFIG_MJPEG_DEMUXER rawdec.c)
add_sources_if (CONFIG_MJPEG_MUXER rawenc.c)
add_sources_if (CONFIG_MLP_DEMUXER rawdec.c mlpdec.c)
add_sources_if (CONFIG_MLP_MUXER rawenc.c)
add_sources_if (CONFIG_MLV_DEMUXER mlvdec.c riffdec.c)
add_sources_if (CONFIG_MM_DEMUXER mm.c)
add_sources_if (CONFIG_MMF_DEMUXER mmf.c)
add_sources_if (CONFIG_MMF_MUXER mmf.c rawenc.c)
add_sources_if (CONFIG_MODS_DEMUXER mods.c)
add_sources_if (CONFIG_MOFLEX_DEMUXER moflex.c)
add_sources_if (CONFIG_MOV_DEMUXER mov.c mov_chan.c mov_esds.c
                                            qtpalette.c replaygain.c dovi_isom.c
                                            dvdclut.c)
add_sources_if (CONFIG_MOV_MUXER movenc.c
                                            movenchint.c mov_chan.c rtp.c
                                            movenccenc.c movenc_ttml.c rawutils.c
                                            apv.c dovi_isom.c evc.c)
add_sources_if (CONFIG_MP2_MUXER rawenc.c)
add_sources_if (CONFIG_MP3_DEMUXER mp3dec.c replaygain.c)
add_sources_if (CONFIG_MP3_MUXER mp3enc.c rawenc.c id3v2enc.c)
add_sources_if (CONFIG_MPC_DEMUXER mpc.c apetag.c img2.c)
add_sources_if (CONFIG_MPC8_DEMUXER mpc8.c apetag.c img2.c)
add_sources_if (CONFIG_MPEG1SYSTEM_MUXER mpegenc.c)
add_sources_if (CONFIG_MPEG1VCD_MUXER mpegenc.c)
add_sources_if (CONFIG_MPEG1VIDEO_MUXER rawenc.c)
add_sources_if (CONFIG_MPEG2DVD_MUXER mpegenc.c)
add_sources_if (CONFIG_MPEG2SVCD_MUXER mpegenc.c)
add_sources_if (CONFIG_MPEG2VIDEO_MUXER rawenc.c)
add_sources_if (CONFIG_MPEG2VOB_MUXER mpegenc.c)
add_sources_if (CONFIG_MPEGPS_DEMUXER mpeg.c)
add_sources_if (CONFIG_MPEGTS_DEMUXER mpegts.c)
add_sources_if (CONFIG_MPEGTS_MUXER mpegtsenc.c)
add_sources_if (CONFIG_MPEGVIDEO_DEMUXER mpegvideodec.c rawdec.c)
add_sources_if (CONFIG_MPJPEG_DEMUXER mpjpegdec.c)
add_sources_if (CONFIG_MPJPEG_MUXER mpjpeg.c)
add_sources_if (CONFIG_MPL2_DEMUXER mpl2dec.c subtitles.c)
add_sources_if (CONFIG_MSF_DEMUXER msf.c)
add_sources_if (CONFIG_MPSUB_DEMUXER mpsubdec.c subtitles.c)
add_sources_if (CONFIG_MSNWC_TCP_DEMUXER msnwc_tcp.c)
add_sources_if (CONFIG_MSP_DEMUXER mspdec.c)
add_sources_if (CONFIG_MTAF_DEMUXER mtaf.c)
add_sources_if (CONFIG_MTV_DEMUXER mtv.c)
add_sources_if (CONFIG_MUSX_DEMUXER musx.c)
add_sources_if (CONFIG_MV_DEMUXER mvdec.c)
add_sources_if (CONFIG_MVI_DEMUXER mvi.c)
add_sources_if (CONFIG_MXF_DEMUXER mxfdec.c mxf.c avlanguage.c)
add_sources_if (CONFIG_MXF_MUXER mxfenc.c mxf.c)
add_sources_if (CONFIG_MXG_DEMUXER mxg.c)
add_sources_if (CONFIG_NC_DEMUXER ncdec.c)
add_sources_if (CONFIG_NISTSPHERE_DEMUXER nistspheredec.c pcm.c)
add_sources_if (CONFIG_NSP_DEMUXER nspdec.c pcm.c)
add_sources_if (CONFIG_NSV_DEMUXER nsvdec.c)
add_sources_if (CONFIG_NULL_MUXER nullenc.c)
add_sources_if (CONFIG_NUT_DEMUXER nutdec.c nut.c)
add_sources_if (CONFIG_NUT_MUXER nutenc.c nut.c)
add_sources_if (CONFIG_NUV_DEMUXER nuv.c)
add_sources_if (CONFIG_AV1_DEMUXER av1dec.c)
add_sources_if (CONFIG_OBU_DEMUXER av1dec.c)
add_sources_if (CONFIG_OBU_MUXER rawenc.c)
add_sources_if (CONFIG_OGG_DEMUXER oggdec.c
                                            oggparsedirac.c
                                            oggparseflac.c
                                            oggparseogm.c
                                            oggparseopus.c
                                            oggparseskeleton.c
                                            oggparsespeex.c
                                            oggparsetheora.c
                                            oggparsevorbis.c
                                            oggparsevp8.c
                                            replaygain.c
                                            vorbiscomment.c
                                            flac_picture.c)
add_sources_if (CONFIG_OGA_MUXER oggenc.c vorbiscomment.c)
add_sources_if (CONFIG_OGG_MUXER oggenc.c vorbiscomment.c)
add_sources_if (CONFIG_OGV_MUXER oggenc.c vorbiscomment.c)
add_sources_if (CONFIG_OMA_DEMUXER omadec.c pcm.c oma.c)
add_sources_if (CONFIG_OMA_MUXER omaenc.c rawenc.c oma.c id3v2enc.c)
add_sources_if (CONFIG_OPUS_MUXER oggenc.c vorbiscomment.c)
add_sources_if (CONFIG_OSQ_DEMUXER osq.c rawdec.c)
add_sources_if (CONFIG_PAF_DEMUXER paf.c)
add_sources_if (CONFIG_PCM_ALAW_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_ALAW_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_F32BE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_F32BE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_F32LE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_F32LE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_F64BE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_F64BE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_F64LE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_F64LE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_MULAW_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_MULAW_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_S16BE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_S16BE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_S16LE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_S16LE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_S24BE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_S24BE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_S24LE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_S24LE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_S32BE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_S32BE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_S32LE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_S32LE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_S8_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_S8_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_U16BE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_U16BE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_U16LE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_U16LE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_U24BE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_U24BE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_U24LE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_U24LE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_U32BE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_U32BE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_U32LE_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_U32LE_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_U8_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_U8_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PCM_VIDC_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_PCM_VIDC_MUXER pcmenc.c rawenc.c)
add_sources_if (CONFIG_PDV_DEMUXER pdvdec.c)
add_sources_if (CONFIG_PDV_MUXER pdvenc.c)
add_sources_if (CONFIG_PJS_DEMUXER pjsdec.c subtitles.c)
add_sources_if (CONFIG_PMP_DEMUXER pmpdec.c)
add_sources_if (CONFIG_PP_BNK_DEMUXER pp_bnk.c)
add_sources_if (CONFIG_PVA_DEMUXER pva.c)
add_sources_if (CONFIG_PVF_DEMUXER pvfdec.c pcm.c)
add_sources_if (CONFIG_QCP_DEMUXER qcp.c)
add_sources_if (CONFIG_QOA_DEMUXER qoadec.c)
add_sources_if (CONFIG_R3D_DEMUXER r3d.c)
add_sources_if (CONFIG_RAWVIDEO_DEMUXER rawvideodec.c)
add_sources_if (CONFIG_RAWVIDEO_MUXER rawenc.c)
add_sources_if (CONFIG_RCWT_DEMUXER rcwtdec.c subtitles.c)
add_sources_if (CONFIG_RCWT_MUXER rcwtenc.c subtitles.c)
add_sources_if (CONFIG_REALTEXT_DEMUXER realtextdec.c subtitles.c)
add_sources_if (CONFIG_REDSPARK_DEMUXER redspark.c)
add_sources_if (CONFIG_RKA_DEMUXER rka.c apetag.c img2.c)
add_sources_if (CONFIG_RL2_DEMUXER rl2.c)
add_sources_if (CONFIG_RM_DEMUXER rmdec.c rm.c rmsipr.c)
add_sources_if (CONFIG_RM_MUXER rmenc.c rm.c)
add_sources_if (CONFIG_ROQ_DEMUXER idroqdec.c)
add_sources_if (CONFIG_ROQ_MUXER idroqenc.c rawenc.c)
add_sources_if (CONFIG_RSD_DEMUXER rsd.c)
add_sources_if (CONFIG_RPL_DEMUXER rpl.c)
add_sources_if (CONFIG_RSO_DEMUXER rsodec.c rso.c pcm.c)
add_sources_if (CONFIG_RSO_MUXER rsoenc.c rso.c rawenc.c)
add_sources_if (CONFIG_RTP_MPEGTS_MUXER rtpenc_mpegts.c)
add_sources_if (CONFIG_RTP_MUXER 
       rtp.c
       rtpenc_aac.c
       rtpenc_latm.c
       rtpenc_amr.c
       rtpenc_av1.c
       rtpenc_h261.c
       rtpenc_h263.c
       rtpenc_h263_rfc2190.c
       rtpenc_h264_hevc.c
       rtpenc_jpeg.c
       rtpenc_mpv.c
       rtpenc.c
       rtpenc_rfc4175.c
       rtpenc_vc2hq.c
       rtpenc_vp8.c
       rtpenc_vp9.c
       rtpenc_xiph.c)
add_sources_if (CONFIG_RTSP_DEMUXER rtsp.c rtspdec.c httpauth.c)
add_sources_if (CONFIG_RTSP_MUXER rtsp.c rtspenc.c httpauth.c)
add_sources_if (CONFIG_S337M_DEMUXER s337m.c spdif.c)
add_sources_if (CONFIG_SAMI_DEMUXER samidec.c subtitles.c)
add_sources_if (CONFIG_SAP_DEMUXER sapdec.c)
add_sources_if (CONFIG_SAP_MUXER sapenc.c)
add_sources_if (CONFIG_SBC_DEMUXER sbcdec.c rawdec.c)
add_sources_if (CONFIG_SBC_MUXER rawenc.c)
add_sources_if (CONFIG_SBG_DEMUXER sbgdec.c)
add_sources_if (CONFIG_SCC_DEMUXER sccdec.c subtitles.c)
add_sources_if (CONFIG_SCC_MUXER sccenc.c)
add_sources_if (CONFIG_SCD_DEMUXER scd.c)
add_sources_if (CONFIG_SDNS_DEMUXER sdns.c)
add_sources_if (CONFIG_SDP_DEMUXER rtsp.c)
add_sources_if (CONFIG_SDR2_DEMUXER sdr2.c)
add_sources_if (CONFIG_SDS_DEMUXER sdsdec.c)
add_sources_if (CONFIG_SDX_DEMUXER sdxdec.c pcm.c)
add_sources_if (CONFIG_SEGAFILM_DEMUXER segafilm.c)
add_sources_if (CONFIG_SEGAFILM_MUXER segafilmenc.c)
add_sources_if (CONFIG_SEGMENT_MUXER segment.c)
add_sources_if (CONFIG_SER_DEMUXER serdec.c)
add_sources_if (CONFIG_SGA_DEMUXER sga.c)
add_sources_if (CONFIG_SHORTEN_DEMUXER shortendec.c rawdec.c)
add_sources_if (CONFIG_SIFF_DEMUXER siff.c)
add_sources_if (CONFIG_SIMBIOSIS_IMX_DEMUXER imx.c)
add_sources_if (CONFIG_SLN_DEMUXER pcmdec.c pcm.c)
add_sources_if (CONFIG_SMACKER_DEMUXER smacker.c)
add_sources_if (CONFIG_SMJPEG_DEMUXER smjpegdec.c smjpeg.c)
add_sources_if (CONFIG_SMJPEG_MUXER smjpegenc.c smjpeg.c)
add_sources_if (CONFIG_SMOOTHSTREAMING_MUXER smoothstreamingenc.c)
add_sources_if (CONFIG_SMUSH_DEMUXER smush.c)
add_sources_if (CONFIG_SOL_DEMUXER sol.c pcm.c)
add_sources_if (CONFIG_SOX_DEMUXER soxdec.c pcm.c)
add_sources_if (CONFIG_SOX_MUXER soxenc.c rawenc.c)
add_sources_if (CONFIG_SPDIF_DEMUXER spdif.c spdifdec.c)
add_sources_if (CONFIG_SPDIF_MUXER spdif.c spdifenc.c)
add_sources_if (CONFIG_SPEEX_MUXER oggenc.c vorbiscomment.c)
add_sources_if (CONFIG_SRT_DEMUXER srtdec.c subtitles.c)
add_sources_if (CONFIG_SRT_MUXER srtenc.c)
add_sources_if (CONFIG_STL_DEMUXER stldec.c subtitles.c)
add_sources_if (CONFIG_STR_DEMUXER psxstr.c)
add_sources_if (CONFIG_STREAMHASH_MUXER hashenc.c)
add_sources_if (CONFIG_STREAM_SEGMENT_MUXER segment.c)
add_sources_if (CONFIG_SUBVIEWER1_DEMUXER subviewer1dec.c subtitles.c)
add_sources_if (CONFIG_SUBVIEWER_DEMUXER subviewerdec.c subtitles.c)
add_sources_if (CONFIG_SUP_DEMUXER supdec.c)
add_sources_if (CONFIG_SUP_MUXER supenc.c)
add_sources_if (CONFIG_SVAG_DEMUXER svag.c)
add_sources_if (CONFIG_SVS_DEMUXER svs.c)
add_sources_if (CONFIG_SWF_DEMUXER swfdec.c swf.c)
add_sources_if (CONFIG_SWF_MUXER swfenc.c swf.c)
add_sources_if (CONFIG_TAK_DEMUXER takdec.c apetag.c img2.c rawdec.c)
add_sources_if (CONFIG_TEDCAPTIONS_DEMUXER tedcaptionsdec.c subtitles.c)
add_sources_if (CONFIG_TEE_MUXER tee.c tee_common.c)
add_sources_if (CONFIG_THP_DEMUXER thp.c)
add_sources_if (CONFIG_THREEDOSTR_DEMUXER 3dostr.c)
add_sources_if (CONFIG_TIERTEXSEQ_DEMUXER tiertexseq.c)
add_sources_if (CONFIG_MKVTIMESTAMP_V2_MUXER mkvtimestamp_v2.c)
add_sources_if (CONFIG_TMV_DEMUXER tmv.c)
add_sources_if (CONFIG_TRUEHD_DEMUXER rawdec.c mlpdec.c)
add_sources_if (CONFIG_TRUEHD_MUXER rawenc.c)
add_sources_if (CONFIG_TTA_DEMUXER tta.c apetag.c img2.c)
add_sources_if (CONFIG_TTA_MUXER ttaenc.c apetag.c img2.c)
add_sources_if (CONFIG_TTML_MUXER ttmlenc.c)
add_sources_if (CONFIG_TTY_DEMUXER tty.c sauce.c)
add_sources_if (CONFIG_TY_DEMUXER ty.c)
add_sources_if (CONFIG_TXD_DEMUXER txd.c)
add_sources_if (CONFIG_UNCODEDFRAMECRC_MUXER uncodedframecrcenc.c framehash.c)
add_sources_if (CONFIG_USM_DEMUXER usmdec.c)
add_sources_if (CONFIG_V210_DEMUXER rawvideodec.c)
add_sources_if (CONFIG_V210X_DEMUXER rawvideodec.c)
add_sources_if (CONFIG_VAG_DEMUXER vag.c)
add_sources_if (CONFIG_VC1_DEMUXER rawdec.c vc1dec.c)
add_sources_if (CONFIG_VC1_MUXER rawenc.c)
add_sources_if (CONFIG_VC1T_DEMUXER vc1test.c)
add_sources_if (CONFIG_VC1T_MUXER vc1testenc.c)
add_sources_if (CONFIG_VIVIDAS_DEMUXER vividas.c)
add_sources_if (CONFIG_VIVO_DEMUXER vivo.c)
add_sources_if (CONFIG_VMD_DEMUXER sierravmd.c)
add_sources_if (CONFIG_VOBSUB_DEMUXER subtitles.c) # mpeg demuxer is in the dependencies)
add_sources_if (CONFIG_VOC_DEMUXER vocdec.c voc_packet.c voc.c)
add_sources_if (CONFIG_VOC_MUXER vocenc.c voc.c)
add_sources_if (CONFIG_VPK_DEMUXER vpk.c)
add_sources_if (CONFIG_VPLAYER_DEMUXER vplayerdec.c subtitles.c)
add_sources_if (CONFIG_VQF_DEMUXER vqf.c)
add_sources_if (CONFIG_VVC_DEMUXER vvcdec.c rawdec.c)
add_sources_if (CONFIG_VVC_MUXER rawenc.c)
add_sources_if (CONFIG_W64_DEMUXER wavdec.c w64.c pcm.c)
add_sources_if (CONFIG_W64_MUXER wavenc.c w64.c)
add_sources_if (CONFIG_WADY_DEMUXER wady.c pcm.c)
add_sources_if (CONFIG_WAVARC_DEMUXER wavarc.c)
add_sources_if (CONFIG_WAV_DEMUXER wavdec.c pcm.c)
add_sources_if (CONFIG_WAV_MUXER wavenc.c)
add_sources_if (CONFIG_WC3_DEMUXER wc3movie.c)
add_sources_if (CONFIG_WEBM_MUXER matroskaenc.c matroska.c avlanguage.c)
add_sources_if (CONFIG_WEBM_DASH_MANIFEST_MUXER webmdashenc.c)
add_sources_if (CONFIG_WEBM_CHUNK_MUXER webm_chunk.c)
add_sources_if (CONFIG_WEBP_ANIM_DEMUXER webp_anim_dec.c)
add_sources_if (CONFIG_WEBP_MUXER webpenc.c)
add_sources_if (CONFIG_WEBVTT_DEMUXER webvttdec.c subtitles.c)
add_sources_if (CONFIG_WEBVTT_MUXER webvttenc.c)
add_sources_if (CONFIG_WHIP_MUXER whip.c avc.c http.c srtp.c)
add_sources_if (CONFIG_WSAUD_DEMUXER westwood_aud.c)
add_sources_if (CONFIG_WSAUD_MUXER westwood_audenc.c)
add_sources_if (CONFIG_WSD_DEMUXER wsddec.c rawdec.c)
add_sources_if (CONFIG_WSVQA_DEMUXER westwood_vqa.c)
add_sources_if (CONFIG_WTV_DEMUXER wtvdec.c wtv_common.c asf.c)
add_sources_if (CONFIG_WTV_MUXER wtvenc.c wtv_common.c asf.c)
add_sources_if (CONFIG_WV_DEMUXER wvdec.c wv.c apetag.c img2.c)
add_sources_if (CONFIG_WVE_DEMUXER wvedec.c pcm.c)
add_sources_if (CONFIG_WV_MUXER wvenc.c wv.c apetag.c img2.c)
add_sources_if (CONFIG_XA_DEMUXER xa.c)
add_sources_if (CONFIG_XBIN_DEMUXER bintext.c sauce.c)
add_sources_if (CONFIG_XMD_DEMUXER xmd.c pcm.c)
add_sources_if (CONFIG_XMV_DEMUXER xmv.c)
add_sources_if (CONFIG_XVAG_DEMUXER xvag.c)
add_sources_if (CONFIG_XWMA_DEMUXER xwma.c)
add_sources_if (CONFIG_YOP_DEMUXER yop.c)
add_sources_if (CONFIG_YUV4MPEGPIPE_DEMUXER yuv4mpegdec.c)
add_sources_if (CONFIG_YUV4MPEGPIPE_MUXER yuv4mpegenc.c)

# external library muxers/demuxers
add_sources_if (CONFIG_AVISYNTH_DEMUXER avisynth.c)
add_sources_if (CONFIG_CHROMAPRINT_MUXER chromaprint.c)
add_sources_if (CONFIG_LIBGME_DEMUXER libgme.c)
add_sources_if (CONFIG_LIBMODPLUG_DEMUXER libmodplug.c)
add_sources_if (CONFIG_LIBOPENMPT_DEMUXER libopenmpt.c)
add_sources_if (CONFIG_VAPOURSYNTH_DEMUXER vapoursynth.c)

# protocols I/O
add_sources_if (CONFIG_ANDROID_CONTENT_PROTOCOL file.c)
add_sources_if (CONFIG_ASYNC_PROTOCOL async.c)
add_sources_if (CONFIG_BLURAY_PROTOCOL bluray.c)
add_sources_if (CONFIG_CACHE_PROTOCOL cache.c)
add_sources_if (CONFIG_CONCAT_PROTOCOL concat.c)
add_sources_if (CONFIG_CONCATF_PROTOCOL concat.c)
add_sources_if (CONFIG_CRYPTO_PROTOCOL crypto.c)
add_sources_if (CONFIG_DATA_PROTOCOL data_uri.c)
add_sources_if (CONFIG_FFRTMPCRYPT_PROTOCOL rtmpcrypt.c rtmpdigest.c rtmpdh.c)
add_sources_if (CONFIG_FFRTMPHTTP_PROTOCOL rtmphttp.c)
add_sources_if (CONFIG_FILE_PROTOCOL file.c)
add_sources_if (CONFIG_FD_PROTOCOL file.c)
add_sources_if (CONFIG_FTP_PROTOCOL ftp.c)
add_sources_if (CONFIG_GOPHER_PROTOCOL gopher.c)
add_sources_if (CONFIG_GOPHERS_PROTOCOL gopher.c)
add_sources_if (CONFIG_HTTP_PROTOCOL http.c httpauth.c)
add_sources_if (CONFIG_HTTPPROXY_PROTOCOL http.c httpauth.c)
add_sources_if (CONFIG_HTTPS_PROTOCOL http.c httpauth.c)
add_sources_if (CONFIG_ICECAST_PROTOCOL icecast.c)
add_sources_if (CONFIG_MD5_PROTOCOL md5proto.c)
add_sources_if (CONFIG_MMSH_PROTOCOL mmsh.c mms.c asf_tags.c)
add_sources_if (CONFIG_MMST_PROTOCOL mmst.c mms.c asf_tags.c)
add_sources_if (CONFIG_PIPE_PROTOCOL file.c)
add_sources_if (CONFIG_PROMPEG_PROTOCOL prompeg.c)
add_sources_if (CONFIG_RTMP_PROTOCOL rtmpproto.c rtmpdigest.c rtmppkt.c)
add_sources_if (CONFIG_RTMPE_PROTOCOL rtmpproto.c rtmpdigest.c rtmppkt.c)
add_sources_if (CONFIG_RTMPS_PROTOCOL rtmpproto.c rtmpdigest.c rtmppkt.c)
add_sources_if (CONFIG_RTMPT_PROTOCOL rtmpproto.c rtmpdigest.c rtmppkt.c)
add_sources_if (CONFIG_RTMPTE_PROTOCOL rtmpproto.c rtmpdigest.c rtmppkt.c)
add_sources_if (CONFIG_RTMPTS_PROTOCOL rtmpproto.c rtmpdigest.c rtmppkt.c)
add_sources_if (CONFIG_RTP_PROTOCOL rtpproto.c ip.c)
add_sources_if (CONFIG_SCTP_PROTOCOL sctp.c)
add_sources_if (CONFIG_SHARED_PROTOCOL shared.c)
add_sources_if (CONFIG_SRTP_PROTOCOL srtpproto.c srtp.c)
add_sources_if (CONFIG_SUBFILE_PROTOCOL subfile.c)
add_sources_if (CONFIG_TEE_PROTOCOL teeproto.c tee_common.c)
add_sources_if (CONFIG_TCP_PROTOCOL tcp.c)
add_sources_if (CONFIG_IPFS_GATEWAY_PROTOCOL ipfsgateway.c)
add_sources_if (CONFIG_IPNS_GATEWAY_PROTOCOL ipfsgateway.c)
add_sources_if (CONFIG_GNUTLS tls_gnutls.c)
add_sources_if (CONFIG_LIBTLS tls_libtls.c)
add_sources_if (CONFIG_MBEDTLS tls_mbedtls.c)
add_sources_if (CONFIG_OPENSSL tls_openssl.c)
add_sources_if (CONFIG_SECURETRANSPORT tls_securetransport.c)
add_sources_if (CONFIG_SCHANNEL tls_schannel.c)
add_sources_if (CONFIG_TLS_PROTOCOL tls.c)
add_sources_if (CONFIG_DTLS_PROTOCOL tls.c)
add_sources_if (CONFIG_UDP_PROTOCOL udp.c ip.c)
add_sources_if (CONFIG_UDPLITE_PROTOCOL udp.c ip.c)
add_sources_if (CONFIG_UNIX_PROTOCOL unix.c)

# external library protocols
add_sources_if (CONFIG_LIBAMQP_PROTOCOL libamqp.c)
add_sources_if (CONFIG_LIBRIST_PROTOCOL librist.c)
add_sources_if (CONFIG_LIBRTMP_PROTOCOL librtmp.c)
add_sources_if (CONFIG_LIBRTMPE_PROTOCOL librtmp.c)
add_sources_if (CONFIG_LIBRTMPS_PROTOCOL librtmp.c)
add_sources_if (CONFIG_LIBRTMPT_PROTOCOL librtmp.c)
add_sources_if (CONFIG_LIBRTMPTE_PROTOCOL librtmp.c)
add_sources_if (CONFIG_LIBSMBCLIENT_PROTOCOL libsmbclient.c)
add_sources_if (CONFIG_LIBSRT_PROTOCOL libsrt.c)
add_sources_if (CONFIG_LIBSSH_PROTOCOL libssh.c)
add_sources_if (CONFIG_LIBZMQ_PROTOCOL libzmq.c)

if (CONFIG_PIC)
    set_target_properties(${TARGET} PROPERTIES
        POSITION_INDEPENDENT_CODE ON
    )

    target_compile_definitions(${TARGET} PRIVATE PIC)
endif ()

# libavdevice dependencies

# Windows resource file
#SHLIBOBJS-$(HAVE_GNU_WINDRES)            += avformatres.c

target_link_libraries (${TARGET} PRIVATE OpenSSL::Crypto)